kind: pipeline
type: docker
name: Hello World Build

trigger:
  branch:
    - main

steps:
  - name: Build Docker Image
    image: docker:24-dind
    privileged: true  # Must for DinD
    commands:
      - echo -e "FROM alpine\nCMD [\"echo\",\"Hello, Drone CI!\"]" > Dockerfile
      - docker build -t hello-drone:latest .
      - docker run hello-drone:latest


