kind: pipeline
type: docker
name: Hello World Build

trigger:
  branch:
    - main

steps:
  - name: Build Docker Image
    image: docker:latest
    commands:
      # Simple Hello World Dockerfile create
      - echo -e "FROM alpine\nCMD [\"echo\",\"Hello, Drone CI!\"]" > Dockerfile
      # Build Docker image
      - docker build -t hello-drone:latest .
      # Run image to see output in logs
      - docker run hello-drone:latest


